**Time Converter

In [1]:
import pandas as pd

In [2]:
import pandas as pd
#load excel
df = pd.read_csv("C:\\Users\\taslim.siddiqui\\Downloads\\production_recoRatingDataRecords (2).csv")
#df=pd.read_excel("//Users//romitbenkar//Desktop//Office//07-11-2024//other_output.xlsx")

# Replace 'apple' with 'orange' and 'banana' with 'grape' in column 'B'
df['duration_medium__c'] = df['duration_medium__c'].replace({'Day': 'Days', 'Month': 'Months','Year':'Years'})

# Define conversion factors to seconds for each mode
conversion_factors = {
    'years': 365 * 24 * 60 * 60,        # approximate (ignores leap years)
    'months': 30.44 * 24 * 60 * 60,     # average month
    'weeks': 7 * 24 * 60 * 60,
    'days': 24 * 60 * 60,
    'hours': 60 * 60,
    'minutes': 60
}

df['duration_medium__c']=df['duration_medium__c'].astype(str)


# Function to convert duration based on the mode
def convert_to_seconds(row):
    duration = row['course_duration__c']
    mode = row['duration_medium__c'].strip().lower()  # normalize to lowercase
    return duration * conversion_factors.get(mode, 1)  # Default to 1 if mode is not found

# Apply the conversion function to each row
df['Duration_in_seconds'] = df.apply(convert_to_seconds, axis=1)

# Add a column that checks if the duration in seconds is less than or equal to a week
df['Is_within_a_week'] = df['Duration_in_seconds'] <= 7 * 24 * 60 * 60

# Save the result back to Excel
#df.to_excel('//Users//romitbenkar//Desktop//Office//19-11-24//timeconvertoutput.xlsx', index=False)
df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,inr_amount__c,skill_id,concepts,Duration_in_seconds,Is_within_a_week
0,01t8n000000GrJPAA0,4641,17890,Amity Future Academy,PG Program in Digital Marketing Strategies (PG...,Advanced,Months,12.00,NaN,170000.0,170000.0,663,9830,31560192.0,False
1,01t8n000000GrJQAA0,4642,16262,Amity Future Academy,PG Program in Product Management (PGP-PM),Advanced,Months,12.00,NaN,215000.0,215000.0,76,6978,31560192.0,False
2,01t8n000000GrJRAA0,4643,16885,Amity Future Academy,Post Graduate Diploma in Management,Advanced,Months,6.00,NaN,120000.0,120000.0,643,"9585 , 9593 , 9594",15780096.0,False
3,01t8n000000GrJSAA0,4644,17637,Amity Future Academy,Post Graduate Diploma in Management,Advanced,Months,6.00,NaN,120000.0,120000.0,343,7066,15780096.0,False
4,01t8n000000GrJTAA0,4645,15978,Amity Future Academy,Post Graduate Program in Big Data Architecture...,Advanced,Months,6.00,NaN,100000.0,100000.0,64,"4928 , 4936",15780096.0,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21369,przzd0g0p1,28069,26535,Udemy,Email Marketing: Subscriber List Growth With C...,Beginner,Minutes,215.00,23850.0,23850.0,23850.0,107,6615,12900.0,True
21370,przzj4igrr,14130,14308,Coursera,Resourcing a Project Schedule,Beginner,Hours,0.30,1.0,0.0,0.0,37,4590,1080.0,True
21371,przzltt2yl,34946,35729,GVC,"Programming Languages, Part B",Intermediate,Hours,18.00,NaN,1.0,1.0,164,6893,64800.0,True
21372,przzvn6z59,14710,11674,Coursera,Exam Prep CKA: Certified Kubernetes Administrator,Intermediate,Hours,18.93,1.0,0.0,0.0,107,NaN,68148.0,True
21373,przzxluxi8,20241,12028,Coursera,Generative AI Primer,Beginner,Hours,1.48,1.0,0.0,0.0,645,9607,5328.0,True

Integration

In [3]:
values_to_check = ['Guvi Geeks','Edujournal','Sharpener','Business Toys Skills School']

# Check if any values in the DataFrame are in the list
df['Integration'] = df['course_provider_platform_name__c'].isin(values_to_check)
df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,inr_amount__c,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration
0,01t8n000000GrJPAA0,4641,17890,Amity Future Academy,PG Program in Digital Marketing Strategies (PG...,Advanced,Months,12.00,NaN,170000.0,170000.0,663,9830,31560192.0,False,False
1,01t8n000000GrJQAA0,4642,16262,Amity Future Academy,PG Program in Product Management (PGP-PM),Advanced,Months,12.00,NaN,215000.0,215000.0,76,6978,31560192.0,False,False
2,01t8n000000GrJRAA0,4643,16885,Amity Future Academy,Post Graduate Diploma in Management,Advanced,Months,6.00,NaN,120000.0,120000.0,643,"9585 , 9593 , 9594",15780096.0,False,False
3,01t8n000000GrJSAA0,4644,17637,Amity Future Academy,Post Graduate Diploma in Management,Advanced,Months,6.00,NaN,120000.0,120000.0,343,7066,15780096.0,False,False
4,01t8n000000GrJTAA0,4645,15978,Amity Future Academy,Post Graduate Program in Big Data Architecture...,Advanced,Months,6.00,NaN,100000.0,100000.0,64,"4928 , 4936",15780096.0,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21369,przzd0g0p1,28069,26535,Udemy,Email Marketing: Subscriber List Growth With C...,Beginner,Minutes,215.00,23850.0,23850.0,23850.0,107,6615,12900.0,True,False
21370,przzj4igrr,14130,14308,Coursera,Resourcing a Project Schedule,Beginner,Hours,0.30,1.0,0.0,0.0,37,4590,1080.0,True,False
21371,przzltt2yl,34946,35729,GVC,"Programming Languages, Part B",Intermediate,Hours,18.00,NaN,1.0,1.0,164,6893,64800.0,True,False
21372,przzvn6z59,14710,11674,Coursera,Exam Prep CKA: Certified Kubernetes Administrator,Intermediate,Hours,18.93,1.0,0.0,0.0,107,NaN,68148.0,True,False
21373,przzxluxi8,20241,12028,Coursera,Generative AI Primer,Beginner,Hours,1.48,1.0,0.0,0.0,645,9607,5328.0,True,False

Concept Count

In [4]:
def count_commas(val):
    if pd.isna(val):
        return 0
    elif ',' in val:
        return val.count(',') + 1
    else:
        return 1
df['concept_count']=df['concepts'].apply(count_commas)
df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,inr_amount__c,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count
0,01t8n000000GrJPAA0,4641,17890,Amity Future Academy,PG Program in Digital Marketing Strategies (PG...,Advanced,Months,12.00,NaN,170000.0,170000.0,663,9830,31560192.0,False,False,1
1,01t8n000000GrJQAA0,4642,16262,Amity Future Academy,PG Program in Product Management (PGP-PM),Advanced,Months,12.00,NaN,215000.0,215000.0,76,6978,31560192.0,False,False,1
2,01t8n000000GrJRAA0,4643,16885,Amity Future Academy,Post Graduate Diploma in Management,Advanced,Months,6.00,NaN,120000.0,120000.0,643,"9585 , 9593 , 9594",15780096.0,False,False,3
3,01t8n000000GrJSAA0,4644,17637,Amity Future Academy,Post Graduate Diploma in Management,Advanced,Months,6.00,NaN,120000.0,120000.0,343,7066,15780096.0,False,False,1
4,01t8n000000GrJTAA0,4645,15978,Amity Future Academy,Post Graduate Program in Big Data Architecture...,Advanced,Months,6.00,NaN,100000.0,100000.0,64,"4928 , 4936",15780096.0,False,False,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21369,przzd0g0p1,28069,26535,Udemy,Email Marketing: Subscriber List Growth With C...,Beginner,Minutes,215.00,23850.0,23850.0,23850.0,107,6615,12900.0,True,False,1
21370,przzj4igrr,14130,14308,Coursera,Resourcing a Project Schedule,Beginner,Hours,0.30,1.0,0.0,0.0,37,4590,1080.0,True,False,1
21371,przzltt2yl,34946,35729,GVC,"Programming Languages, Part B",Intermediate,Hours,18.00,NaN,1.0,1.0,164,6893,64800.0,True,False,1
21372,przzvn6z59,14710,11674,Coursera,Exam Prep CKA: Certified Kubernetes Administrator,Intermediate,Hours,18.93,1.0,0.0,0.0,107,NaN,68148.0,True,False,0
21373,przzxluxi8,20241,12028,Coursera,Generative AI Primer,Beginner,Hours,1.48,1.0,0.0,0.0,645,9607,5328.0,True,False,1

No concept column

In [5]:
deficit_0 =(df['concept_count']== 0 ).sum()
deficit_0

2431

In [6]:
df['no_concept'] = df['concepts'].isna()

## Only priority CPP

In [7]:
values_to_check_priority_cpp = ['Henry Harvin Education','Henry Harvin','Eduonix']

# Check if any values in the DataFrame are in the list
df['priority_cpp'] = df['course_provider_platform_name__c'].isin(values_to_check_priority_cpp)
priority_cpp_df = df.query("priority_cpp == True and no_concept == False")
priority_cpp_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,inr_amount__c,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp
92,01t8n000000GrYnAAK,5587,15679,Eduonix,AI-ML For Absolute Beginners E-Degree,Beginner,Hours,35.0,39500.0,7900.0,7900.0,65,"4673 , 5224",126000.0,True,False,2,False,True
159,01t8n000000GrfBAAS,5991,17553,Henry Harvin,7 QC Tools Course,Beginner,Hours,8.0,9500.0,5000.0,5000.0,645,9607,28800.0,True,False,1,False,True
163,01t8n000000GrfGAAS,5996,15983,Henry Harvin,ACCA Course Training,Advanced,Hours,900.0,NaN,93000.0,93000.0,630,"9475 , 9476",3240000.0,False,False,2,False,True
164,01t8n000000GrfHAAS,5997,16790,Henry Harvin,ACCA Dip. IFRS Course,Advanced,Hours,75.0,NaN,29500.0,29500.0,630,9476,270000.0,True,False,1,False,True
165,01t8n000000GrfIAAS,5998,17412,Henry Harvin,Accounting and Taxation Course,Advanced,Hours,172.0,NaN,34500.0,34500.0,648,"9634 , 9636 , 9638 , 9644",619200.0,False,False,4,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21261,przseu9ihh,32571,32384,Henry Harvin,Lean Six Sigma Combo (Green Belt + PMP) Course...,Beginner,Hours,64.0,32500.0,32500.0,32500.0,261,5024,230400.0,True,False,1,False,True
21265,przst9nk8u,32231,32044,Henry Harvin,CompTIA Cloud+ CV0-003 Training Course (Instru...,Beginner,Hours,40.0,22500.0,22500.0,22500.0,58,5723,144000.0,True,False,1,False,True
21269,przsx3so8g,32315,32128,Henry Harvin,Content Writing Course with Gold Membership (I...,Beginner,Hours,40.0,17500.0,17500.0,17500.0,129,4539,144000.0,True,False,1,False,True
21337,przxanp6v0,21027,18953,Eduonix,ChatGPT & Generative AI Lifetime Membership,Beginner,Hours,75.0,22000.0,14950.0,14950.0,645,9607,270000.0,True,False,1,False,True
21346,przxtoqmej,21015,18941,Eduonix,MERN Stack Developer E-Degree Program,Beginner,Hours,20.0,5300.0,5300.0,5300.0,57,6446,72000.0,True,False,1,False,True

In [8]:
# Check if any values in the DataFrame are in the list
df['priority_cpp'] = df['course_provider_platform_name__c'].isin(values_to_check_priority_cpp)
priority_cpp_0_df = df.query("priority_cpp == True and no_concept == True")
priority_cpp_0_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,inr_amount__c,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp
93,01t8n000000GrYpAAK,5589,16949,Eduonix,Live Data Science Certification Program,Advanced,Months,6.00,79999.0,79999.0,79999.0,69,NaN,15780096.0,False,False,0,True,True
141,01t8n000000Grd6AAC,5862,17470,Henry Harvin,Post Graduate Diploma in Human Rights,Advanced,Months,9.00,NaN,25500.0,25500.0,64,NaN,23670144.0,False,False,0,True,True
158,01t8n000000GrfAAAS,5990,17589,Henry Harvin,5S Certification Training Course,Beginner,Hours,8.00,NaN,5000.0,5000.0,37,NaN,28800.0,True,False,0,True,True
160,01t8n000000GrfCAAS,5992,16788,Henry Harvin,8051 and Arduino Course,Beginner,Hours,40.00,NaN,34500.0,34500.0,213,NaN,144000.0,True,False,0,True,True
161,01t8n000000GrfEAAS,5994,17401,Henry Harvin,8D Analysis Course,Beginner,Hours,8.00,9500.0,9500.0,9500.0,37,NaN,28800.0,True,False,0,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18037,prt8u1g23p,32871,32719,Henry Harvin,Certificate Course in Investment Law (Instruct...,Beginner,Hours,35.00,22500.0,22500.0,22500.0,389,NaN,126000.0,True,False,0,True,True
18239,prtlz4fi6q,32875,32723,Henry Harvin,Business Analysis Course Training (Instructor-...,Beginner,Hours,24.00,15000.0,15000.0,15000.0,39,NaN,86400.0,True,False,0,True,True
18777,pruqhr0m95,21038,18964,Eduonix,Learn Oracle Process Cloud,Beginner,Hours,5.47,5000.0,5000.0,5000.0,108,NaN,19692.0,True,False,0,True,True
19001,prv7ba4hn6,33647,34145,Henry Harvin,Executive Certification Course in Human Resour...,Intermediate,Hours,288.00,118000.0,118000.0,118000.0,27,NaN,1036800.0,False,False,0,True,True
19233,prvp5xxwba,33597,33496,Henry Harvin,MBA in Digital Marketing,Beginner,Hours,192.00,298000.0,298000.0,298000.0,107,NaN,691200.0,False,False,0,True,True

Only Udemy data

In [9]:

# Sample DataFrame
df# data is the file which will only have CPP names

# List of values to check
values_to_check_udemy = ['Udemy']

# Check if any values in the DataFrame are in the list
df['Udemy'] = df['course_provider_platform_name__c'].isin(values_to_check_udemy)
udemy_df = df.query("Udemy == True and no_concept == False")
udemy_df
#df.to_excel("//Users//romitbenkar//Desktop//Office//19-11-2024//Udemy_output.xlsx")

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,inr_amount__c,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp,Udemy
1419,0AbIh9To,24901,23122,Udemy,"(Jetpack, Architecture and More)Advanced Andro...",Beginner,Minutes,2250.0,23850.0,23850.0,23850.0,293,6876,135000.0,True,False,1,False,False,True
1420,0AbXa8Ut,24645,22866,Udemy,Object-oriented Programming in JavaScript,Intermediate,Minutes,234.0,23850.0,23850.0,23850.0,103,6849,14040.0,True,False,1,False,False,True
1421,0AnKw5Rl,24128,22349,Udemy,Vue - The Complete Guide (incl. Router and C...,Beginner,Minutes,1912.0,23850.0,23850.0,23850.0,103,6849,114720.0,True,False,1,False,False,True
1422,0ArCd7Lv,27407,25631,Udemy,Bootstrap 5 From Scratch | Build 5 Modern Webs...,Beginner,Minutes,798.0,23850.0,23850.0,23850.0,103,"6817 , 6849",47880.0,True,False,2,False,False,True
1423,0ArKm5Sb,24969,23190,Udemy,Complete Deep Learning In R With Keras and Others,Beginner,Minutes,475.0,23850.0,23850.0,23850.0,293,6778,28500.0,True,False,1,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21349,przy1fgag3,28644,27110,Udemy,Microsoft Teams: Teams Essentials for the work...,Beginner,Minutes,135.0,23850.0,23850.0,23850.0,44,4561,8100.0,True,False,1,False,False,True
21354,przyc3rjqv,31300,29856,Udemy,Master Certified Fraud Examiner (CFE) Essentia...,Beginner,Minutes,121.0,0.0,23850.0,23850.0,24,5635,7260.0,True,False,1,False,False,True
21355,przyhu62lv,29152,27615,Udemy,Negotiating Your Salary and Compensation,Beginner,Minutes,133.0,23850.0,23850.0,23850.0,643,9588,7980.0,True,False,1,False,False,True
21365,przyxra2de,29045,27508,Udemy,Advanced Cryptography Concepts,Beginner,Minutes,260.0,23850.0,23850.0,23850.0,291,4648,15600.0,True,False,1,False,False,True
21369,przzd0g0p1,28069,26535,Udemy,Email Marketing: Subscriber List Growth With C...,Beginner,Minutes,215.0,23850.0,23850.0,23850.0,107,6615,12900.0,True,False,1,False,False,True

In [10]:
# Check if any values in the DataFrame are in the list
df['Udemy'] = df['course_provider_platform_name__c'].isin(values_to_check_udemy)
udemy_0_df = df.query("Udemy == True and no_concept == True")
udemy_0_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,inr_amount__c,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp,Udemy
1741,1FkNf0Wo,22871,21092,Udemy,ACCA MA (F2) A Complete Course on Management A...,Beginner,Minutes,2014.0,23850.0,23850.0,23850.0,261,NaN,120840.0,True,False,0,True,False,True
1993,2FeBo7Oj,25745,23967,Udemy,AWS Technical Essentials - Hands-On Training ...,Beginner,Minutes,866.0,23850.0,23850.0,23850.0,44,NaN,51960.0,True,False,0,True,False,True
2877,5TgAx9Cg,22983,21204,Udemy,Certified Key Performance Indicators Professio...,Beginner,Minutes,448.0,23850.0,23850.0,23850.0,49,NaN,26880.0,True,False,0,True,False,True
2930,5YrGr8Hy,22895,21116,Udemy,Automated Cryptocurrency Portfolio Investing w...,Beginner,Minutes,1931.0,23850.0,23850.0,23850.0,49,NaN,115860.0,True,False,0,True,False,True
3226,7BpKm9Gj,23448,21669,Udemy,"Master PMP Cost Management: Plan, Budget, Esti...",Beginner,Minutes,224.0,23850.0,23850.0,23850.0,49,NaN,13440.0,True,False,0,True,False,True
3607,8ObDt0Ty,23451,21672,Udemy,Master SWOT Analysis and Business Strategy f...,Beginner,Minutes,185.0,23850.0,23850.0,23850.0,49,NaN,11100.0,True,False,0,True,False,True
6006,pr48w18bp0,28040,26506,Udemy,Leadership: Practical Leadership Skills,Beginner,Minutes,200.0,23850.0,23850.0,23850.0,255,NaN,12000.0,True,False,0,True,False,True
6245,pr4rce05qb,30210,28673,Udemy,"Ethical AI Decision Making, Insights for Leade...",Beginner,Minutes,126.0,23850.0,23850.0,23850.0,261,NaN,7560.0,True,False,0,True,False,True
7395,pr72kec05o,27984,26450,Udemy,Lean Six Sigma Green Belt Online Course (2023),Beginner,Minutes,967.0,23850.0,23850.0,23850.0,39,NaN,58020.0,True,False,0,True,False,True
9438,prbg329x5m,28263,26729,Udemy,"Leadership: How to Influence, Inspire and Impa...",Beginner,Minutes,91.0,23850.0,23850.0,23850.0,255,NaN,5460.0,True,False,0,True,False,True
10022,prckjmlvhq,29660,28123,Udemy,Managing a Global Team with Confidence,Beginner,Minutes,35.0,23850.0,23850.0,23850.0,255,NaN,2100.0,True,False,0,True,False,True
10896,preelbycur,29646,28109,Udemy,Leadership - Rise of a Leader (Lead people wit...,Beginner,Minutes,91.0,23850.0,23850.0,23850.0,255,NaN,5460.0,True,False,0,True,False,True
11822,prgh28omad,30150,28613,Udemy,Web Performance In Practice: Master Core Web V...,Beginner,Minutes,204.0,23850.0,23850.0,23850.0,106,NaN,12240.0,True,False,0,True,False,True
12048,prgxo3e70m,29720,28183,Udemy,Leadership Skills: Learn Vigilant Leadership &...,Beginner,Minutes,89.0,23850.0,23850.0,23850.0,255,NaN,5340.0,True,False,0,True,False,True
14302,prllet9osu,30939,29495,Udemy,Manage Change Through Collaboration and Team Work,Beginner,Minutes,102.0,0.0,23850.0,23850.0,262,NaN,6120.0,True,False,0,True,False,True
17035,prr7lx775u,29532,27995,Udemy,Leading & Managing People [Effectively],Beginner,Minutes,119.0,23850.0,23850.0,23850.0,255,NaN,7140.0,True,False,0,True,False,True
17273,prrn4jj0va,28014,26480,Udemy,"Management - Leadership, Negotiating, Assertiv...",Beginner,Minutes,128.0,23850.0,23850.0,23850.0,255,NaN,7680.0,True,False,0,True,False,True
18314,prtq3w17ir,29930,28393,Udemy,Product Owner II for Agile Intermediate: Certi...,Beginner,Minutes,379.0,23850.0,23850.0,23850.0,36,NaN,22740.0,True,False,0,True,False,True
18383,prtvhr73po,28604,27070,Udemy,Visionary Servant Leadership,Beginner,Minutes,84.0,23850.0,23850.0,23850.0,255,NaN,5040.0,True,False,0,True,False,True
19005,prv7lg5yyb,29127,27590,Udemy,Leadership & Management Skills: 2-in-1 Masterc...,Beginner,Minutes,2655.0,23850.0,23850.0,23850.0,255,NaN,159300.0,True,False,0,True,False,True
20199,prxn9li6ss,31017,29573,Udemy,Collaboration with Emotional Intelligence,Intermediate,Minutes,184.0,0.0,23850.0,23850.0,262,NaN,11040.0,True,False,0,True,False,True
20961,prz4qvhvi9,30188,28651,Udemy,Professional Diploma in Advertising and Public...,Beginner,Minutes,251.0,23850.0,23850.0,23850.0,262,NaN,15060.0,True,False,0,True,False,True
21009,prz8qyxwm0,28009,26475,Udemy,"How to Lead with Ease & Be a Successful CEO, L...",Beginner,Minutes,186.0,23850.0,23850.0,23850.0,255,NaN,11160.0,True,False,0,True,False,True

Only ABC data   Priority_ coursera

In [11]:
values_to_check_abc_coursera = ['Coursera']

# Check if values in 'course_provider_platform_name__c' column are in the list, and create a boolean column 'ABC'
df['ABC_coursera'] = df['course_provider_platform_name__c'].isin(values_to_check_abc_coursera)

abc_coursera_df = df.query("ABC_coursera == True and no_concept == False")
abc_coursera_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp,Udemy,ABC_coursera
3988,pr0072y7ai,17054,13847,Coursera,"Personal Productivity, Time Management and Pri...",Beginner,Hours,6.32,1.0,0.0,...,39,5939,22752.0,True,False,1,False,False,False,True
3989,pr00ll9a88,14368,15208,Coursera,Use SurveyMonkey to Create a Survey and Analyz...,Beginner,Hours,0.40,1.0,0.0,...,123,5497,1440.0,True,False,1,False,False,False,True
3990,pr00nc2nuj,19718,12119,Coursera,Getting Started with Facebook Pixel,Beginner,Hours,NaN,1.0,0.0,...,121,4726,NaN,False,False,1,False,False,False,True
4002,pr01mrgb8a,16779,13115,Coursera,LangChain Chat with Your Data,Beginner,Hours,1.50,1.0,0.0,...,213,"5888 , 6107",5400.0,True,False,2,False,False,False,True
4005,pr01x7z7az,16372,15180,Coursera,Use C++ to build a Crypto Trading Platform: Fi...,Intermediate,Hours,7.30,1.0,0.0,...,291,4648,26280.0,True,False,1,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21362,przyv633ju,15093,14071,Coursera,Programming Languages Ⅱ,Intermediate,Hours,10.55,1.0,0.0,...,213,6107,37980.0,True,False,1,False,False,False,True
21366,przz7qgy8j,20005,14847,Coursera,Technical Managerial Written Skills,Beginner,Hours,18.87,1.0,0.0,...,645,9609,67932.0,True,False,1,False,False,False,True
21367,przz9s4oct,16916,10069,Coursera,Building Your Freelancing Career Capstone,Intermediate,Hours,11.93,1.0,0.0,...,37,5396,42948.0,True,False,1,False,False,False,True
21370,przzj4igrr,14130,14308,Coursera,Resourcing a Project Schedule,Beginner,Hours,0.30,1.0,0.0,...,37,4590,1080.0,True,False,1,False,False,False,True
21373,przzxluxi8,20241,12028,Coursera,Generative AI Primer,Beginner,Hours,1.48,1.0,0.0,...,645,9607,5328.0,True,False,1,False,False,False,True

In [12]:
# Check if values in 'course_provider_platform_name__c' column are in the list, and create a boolean column 'ABC'
df['ABC_coursera'] = df['course_provider_platform_name__c'].isin(values_to_check_abc_coursera)

abc_coursera_0_df = df.query("ABC_coursera == True and no_concept == True")
abc_coursera_0_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp,Udemy,ABC_coursera
4048,pr05es3nvi,18844,12909,Coursera,Introduction to NoSQL Databases,Beginner,Hours,NaN,1.0,0.0,...,57,NaN,NaN,False,False,0,True,False,False,True
4063,pr06e8hqrz,14035,14086,Coursera,Project Management: Control using the Earned V...,Beginner,Hours,1.87,1.0,0.0,...,213,NaN,6732.0,True,False,0,True,False,False,True
4098,pr08pu8d3g,19039,14138,Coursera,PyCaret: Anatomy of Classification,Intermediate,Hours,0.20,1.0,0.0,...,65,NaN,720.0,True,False,0,True,False,False,True
4102,pr08wgxixo,17716,19575,Coursera,The Principles of Real Estate,Beginner,Hours,24.13,1.0,0.0,...,213,NaN,86868.0,True,False,0,True,False,False,True
4106,pr091o1o6t,19628,11836,Coursera,FinTech Foundations and Overview,Beginner,Hours,7.20,1.0,0.0,...,262,NaN,25920.0,True,False,0,True,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21306,przvd8bx2g,19471,10883,Coursera,Creating Custom Callbacks in Keras,Intermediate,Hours,0.10,1.0,0.0,...,69,NaN,360.0,True,False,0,True,False,False,True
21333,przx3a7dpa,16113,9655,Coursera,Autoscaling TensorFlow Model Deployments with ...,Intermediate,Hours,1.50,1.0,0.0,...,69,NaN,5400.0,True,False,0,True,False,False,True
21347,przxwst6s4,16924,13794,Coursera,Our Share: Employee Ownership as a Wealth Shar...,Beginner,Hours,15.08,1.0,0.0,...,267,NaN,54288.0,True,False,0,True,False,False,True
21364,przyx8v5ue,14285,10322,Coursera,"Cluster Analysis, Association Mining, and Mode...",Intermediate,Hours,3.95,1.0,0.0,...,68,NaN,14220.0,True,False,0,True,False,False,True
21372,przzvn6z59,14710,11674,Coursera,Exam Prep CKA: Certified Kubernetes Administrator,Intermediate,Hours,18.93,1.0,0.0,...,107,NaN,68148.0,True,False,0,True,False,False,True

In [13]:
# List of values to check
values_to_check_abc = ['GVC','Gyanodaya Virtual Campus','CIEL']

# Check if values in 'course_provider_platform_name__c' column are in the list, and create a boolean column 'ABC'
df['ABC'] = df['course_provider_platform_name__c'].isin(values_to_check_abc)

# Save the updated DataFrame to a new Excel file
#df.to_excel("//Users//romitbenkar//Desktop//Office//07-11-2024//ABCoutput.xlsx", index=False)
abc_df = df.query("ABC == True and no_concept == False")
abc_df
#df.to_excel("//Users//romitbenkar//Desktop//Office//19-11-2024//Udemy_output.xlsx")

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp,Udemy,ABC_coursera,ABC
3987,pr000be54a,22145,20095,GVC,Advanced Visualizations & Dashboards: Visualiz...,Intermediate,Hours,0.34,1.0,0.0,...,4641,1224.0,True,False,1,False,False,False,False,True
3995,pr015bytb9,12844,8295,GVC,CompTIA A+ Core 1: Wireless Networking & Services,Intermediate,Hours,2.25,1.0,0.0,...,6575,8100.0,True,False,1,False,False,False,False,True
3998,pr01iiouag,34882,35609,GVC,Cryptography and Information Theory,Intermediate,Hours,4.60,NaN,1.0,...,4648,16560.0,True,False,1,False,False,False,False,True
3999,pr01kkxugj,12964,8414,GVC,Integrate Power Apps portals with web-based te...,Beginner,Hours,0.19,1.0,0.0,...,5207,684.0,True,False,1,False,False,False,False,True
4000,pr01kw4oyr,22165,20115,GVC,CompTIA A+ Core 1: Mobile Device Accessories &...,Beginner,Hours,1.22,1.0,0.0,...,6229,4392.0,True,False,1,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
21329,przwty7x3c,13212,8662,GVC,Webex Meetings Web: Organizing & Hosting Meetings,Beginner,Hours,1.07,1.0,0.0,...,6226,3852.0,True,False,1,False,False,False,False,True
21353,przy8u5muw,12681,8132,GVC,PMBOK® Guide Sixth Edition: Project Management...,Intermediate,Hours,0.45,1.0,0.0,...,4590,1620.0,True,False,1,False,False,False,False,True
21360,przyr0egej,13596,9046,GVC,Applying Research Methods for Trend & Impact A...,Advanced,Hours,0.35,1.0,0.0,...,5263,1260.0,True,False,1,False,False,False,False,True
21361,przyu0in9m,22779,20873,GVC,Microsoft Azure Services and Lifecycles,Beginner,Hours,NaN,1.0,0.0,...,5947,NaN,False,False,1,False,False,False,False,True
21371,przzltt2yl,34946,35729,GVC,"Programming Languages, Part B",Intermediate,Hours,18.00,NaN,1.0,...,6893,64800.0,True,False,1,False,False,False,False,True

In [14]:
# Save the updated DataFrame to a new Excel file
#df.to_excel("//Users//romitbenkar//Desktop//Office//07-11-2024//ABCoutput.xlsx", index=False)
abc_0_df = df.query("ABC == True and no_concept == True")
abc_0_df
#df.to_excel("//Users//romitbenkar//Desktop//Office//19-11-2024//Udemy_output.xlsx")

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp,Udemy,ABC_coursera,ABC
4433,pr0wj9k13n,13718,9167,GVC,Implement DirectAccess [Guided],Beginner,Hours,0.750,1.0,0.0,...,NaN,2700.0,True,False,0,True,False,False,False,True
4564,pr17mclr8v,13296,8746,GVC,"CompTIA Server+: Ports, Protocols, & Cable Man...",Intermediate,Hours,0.530,1.0,0.0,...,NaN,1908.0,True,False,0,True,False,False,False,True
4602,pr1avov4dr,22840,20934,GVC,Advanced Styling with Responsive Design,Beginner,Hours,NaN,1.0,0.0,...,NaN,NaN,False,False,0,True,False,False,False,True
4842,pr1tp2vzx8,12759,8210,GVC,Windows 8.1: Installing & Using Windows Univer...,Intermediate,Hours,1.280,1.0,0.0,...,NaN,4608.0,True,False,0,True,False,False,False,True
5268,pr2o2gu7to,22776,20870,GVC,Data Engineering with MS Azure Synapse Apache ...,Beginner,Hours,NaN,1.0,0.0,...,NaN,NaN,False,False,0,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
20326,prxw8lype3,20908,18816,GVC,Optimize Your Operations for Today - and Tomorrow,Beginner,Hours,0.580,1.0,0.0,...,NaN,2088.0,True,False,0,True,False,False,False,True
20344,prxxilay2h,21520,19565,GVC,Project Scheduling: Estimate Activity Durations,Beginner,Hours,NaN,1.0,0.0,...,NaN,NaN,False,False,0,True,False,False,False,True
20923,prz1t3b38w,12954,8404,GVC,AWS SysOps Associate 2021: EC2 Instance Manage...,Intermediate,Hours,1.535,1.0,0.0,...,NaN,5526.0,True,False,0,True,False,False,False,True
20928,prz2d9wato,13588,9038,GVC,Slack 2020: Configuring Slack,Intermediate,Hours,NaN,1.0,0.0,...,NaN,NaN,False,False,0,True,False,False,False,True
21224,przp8o0vrj,20929,18837,GVC,Scrum Foundation: Scrum Development Concepts,Beginner,Hours,1.100,1.0,0.0,...,NaN,3960.0,True,False,0,True,False,False,False,True

non_corporate_df(No ABC and Udemy) Wizr course

In [15]:
non_corporate_df = df.query("ABC == False and ABC_coursera == False and Udemy == False and priority_cpp == False  and no_concept == False").sort_values(by='Duration_in_seconds')
non_corporate_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp,Udemy,ABC_coursera,ABC
1311,01t8n000000JE6yAAG,10009,15708,Skill Smith,Angular Master Program Offline,Advanced,Minutes,3.0,5.0,118000.00,...,5747,1.800000e+02,True,False,1,False,False,False,False,False
1316,01t8n000000JE73AAG,10014,15544,Skill Smith,Master React Native Program Online,Advanced,Minutes,3.0,9.0,777.29,...,5747,1.800000e+02,True,False,1,False,False,False,False,False
1308,01t8n000000JE6uAAG,10005,15553,Skill Smith,Full Stack Program (React JS and Node JS) Offline,Advanced,Minutes,6.0,15.0,1295.48,...,5747,3.600000e+02,True,False,1,False,False,False,False,False
1309,01t8n000000JE6vAAG,10006,15552,Skill Smith,Full Stack Program (React JS and Node JS) Online,Advanced,Minutes,6.0,15.0,1295.48,...,6107,3.600000e+02,True,False,1,False,False,False,False,False
12594,pri5rci4yv,35552,36373,PharmaState Academy,Personal Protective Equipment (PPEs) - Safety ...,Beginner,Minutes,7.0,NaN,399.00,...,"7965 , 7966 , 7967 , 7970 , 7971",4.200000e+02,True,False,5,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1010,01t8n000000GwvPAAS,9054,16448,Lovely Professional University,"BBA, LL.B. (Hons.)",Intermediate,Years,5.0,1200000.0,1200000.00,...,5061,1.576800e+08,False,False,1,False,False,False,False,False
472,01t8n000000GrsuAAC,6842,15579,Masters Union,Undergraduate Programme,Beginner,Years,6.0,NaN,2925000.00,...,9802,1.892160e+08,False,False,1,False,False,False,False,False
11560,prfwoo5mcq,27775,25999,IMI Delhi,Post Graduate Diploma in Management (Online),Advanced,Years,24.0,295000.0,295000.00,...,9656,7.568640e+08,False,False,1,False,False,False,False,False
539,01t8n000000GrxEAAS,7140,17371,upGrad,MBA Leading Business Transformation,Advanced,Months,585.0,365000.0,1344753.00,...,5877,1.538559e+09,False,False,1,False,False,False,False,False
85,01t8n000000GrYbAAK,5575,16657,Edudelphi,Certified Fraud Examiner Course in India,Advanced,nan,NaN,NaN,450.00,...,5503,NaN,False,False,1,False,False,False,False,False

In [16]:
non_corporate_0_df = df.query("ABC == False and Udemy == False and ABC_coursera == False and priority_cpp == False and no_concept == True").sort_values(by='Duration_in_seconds')
non_corporate_0_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp,Udemy,ABC_coursera,ABC
12210,prha028n6z,10900,17663,Skillfloor,Certified Data Scientist Professional,Beginner,Month,3.0,40000.0,60000.00,...,NaN,3.0,True,False,0,True,False,False,False,False
14154,prlag2pjhr,27842,26220,Edureka,Linux Administration Certification Training Co...,Beginner,Week,7.5,23594.0,17995.00,...,NaN,7.5,True,False,0,True,False,False,False,False
1084,01t8n000000Gx1RAAS,9428,15717,Unext,Integrated Program In Business Analytics,Advanced,Month,10.0,305836.0,305836.00,...,NaN,10.0,True,False,0,True,False,False,False,False
1310,01t8n000000JE6wAAG,10007,15551,Skill Smith,Java Booster Program Offline,Advanced,Minutes,3.0,15.0,118000.00,...,NaN,180.0,True,False,0,True,False,False,False,False
1315,01t8n000000JE72AAG,10013,16508,Skill Smith,Master React Native Program Offline,Advanced,Minutes,3.0,9.0,777.29,...,NaN,180.0,True,False,0,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1347,01t8n000000KtT5AAK,10214,15523,Yenepoya,Bachelor of Computer Application | Cloud Compu...,Intermediate,Years,4.0,120000.0,120000.00,...,NaN,126144000.0,False,False,0,True,False,False,False,False
5861,pr3yro2h81,11180,15999,Physics Wallah,UG Course in Computer Science & Artificial Int...,Advanced,Years,4.0,1519000.0,1519000.00,...,NaN,126144000.0,False,False,0,True,False,False,False,False
1413,01tTZ000000gwFWYAY,10541,5922,The Design Village Easebuzz,Product Design,Beginner,Years,4.0,2200000.0,2200000.00,...,NaN,126144000.0,False,False,0,True,False,False,False,False
1409,01tTZ000000gwEvYAI,10504,5894,The Design Village Easebuzz,Interaction & Ux Design,Beginner,Years,4.0,2200000.0,2200000.00,...,NaN,126144000.0,False,False,0,True,False,False,False,False
150,01t8n000000GreMAAS,5940,14641,Fireblaze AI School,SQL for Data Science,Advanced,nan,NaN,NaN,2499.00,...,NaN,NaN,False,False,0,True,False,False,False,False

In [17]:
non_corporate_priority_cpp_df = df.query("ABC == False and ABC_coursera == False and Udemy == False and Integration==False and priority_cpp == True").sort_values(by='Duration_in_seconds')
non_corporate_priority_cpp_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp,Udemy,ABC_coursera,ABC
4515,pr140tds7q,21046,18972,Eduonix,Business Analytics for Beginners,Beginner,Minutes,15.00,22488.0,22488.0,...,4980,900.0,True,False,1,False,True,False,False,False
17376,prrv19u96h,21052,18978,Eduonix,Web Accessibility for an Inclusive online pres...,Beginner,Hours,1.00,1500.0,5500.0,...,NaN,3600.0,True,False,0,True,True,False,False,False
19594,prwelgdjic,21043,18969,Eduonix,"Start Simple Coding with HTML , CSS and JavaSc...",Beginner,Hours,1.05,10000.0,10000.0,...,"5102 , 5747",3780.0,True,False,2,False,True,False,False,False
5083,pr2aa9dt8x,21053,18979,Eduonix,UIUX with Figma,Beginner,Hours,1.13,1500.0,5599.0,...,NaN,4068.0,True,False,0,True,True,False,False,False
4313,pr0or3bd6t,21049,18975,Eduonix,Microsoft Bot Framework v4 - Real Life Example...,Beginner,Minutes,68.00,12500.0,12500.0,...,5947,4080.0,True,False,1,False,True,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6674,pr5nenya2u,32958,32806,Henry Harvin,Advanced Human Resource Management Course (Sel...,Advanced,Years,4.00,349500.0,349500.0,...,5586,126144000.0,False,False,1,False,True,False,False,False
6378,pr4zjtodwa,33700,33605,Henry Harvin Education,Industry Expert Program in Finance and Account...,Intermediate,Years,4.00,498000.0,498000.0,...,7056,126144000.0,False,False,1,False,True,False,False,False
19673,prwka30dss,32957,32805,Henry Harvin,Advanced Human Resource Management Course (Liv...,Advanced,Years,4.00,349500.0,349500.0,...,"5586 , 5770",126144000.0,False,False,2,False,True,False,False,False
8389,pr96zqow82,32296,32109,Henry Harvin,Advanced Human Resource Management Course (Ins...,Beginner,Years,4.00,349500.0,349500.0,...,"4799 , 6262 , 6318 , 6461",126144000.0,False,False,4,False,True,False,False,False
16865,prqu6t1ijt,35459,36150,Henry Harvin,Masters (MS) in Digital Marketing,Beginner,Months,288.00,NaN,22500.0,...,5102,757444608.0,False,False,1,False,True,False,False,False

Ranking non_corporate

In [18]:
non_corporate_df = non_corporate_df.sort_values(
    by=["Duration_in_seconds", "Integration", "inr_amount__c"],
    ascending=[True, False, True]
).reset_index(drop=True)

# Assign sequence rankings based on sorted order
non_corporate_df['Rank'] = 600 - (non_corporate_df.index * 0.01)
non_corporate_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp,Udemy,ABC_coursera,ABC,Rank
0,01t8n000000JE73AAG,10014,15544,Skill Smith,Master React Native Program Online,Advanced,Minutes,3.0,9.0,777.29,...,1.800000e+02,True,False,1,False,False,False,False,False,600.00
1,01t8n000000JE6yAAG,10009,15708,Skill Smith,Angular Master Program Offline,Advanced,Minutes,3.0,5.0,118000.00,...,1.800000e+02,True,False,1,False,False,False,False,False,599.99
2,01t8n000000JE6uAAG,10005,15553,Skill Smith,Full Stack Program (React JS and Node JS) Offline,Advanced,Minutes,6.0,15.0,1295.48,...,3.600000e+02,True,False,1,False,False,False,False,False,599.98
3,01t8n000000JE6vAAG,10006,15552,Skill Smith,Full Stack Program (React JS and Node JS) Online,Advanced,Minutes,6.0,15.0,1295.48,...,3.600000e+02,True,False,1,False,False,False,False,False,599.97
4,pri5rci4yv,35552,36373,PharmaState Academy,Personal Protective Equipment (PPEs) - Safety ...,Beginner,Minutes,7.0,NaN,399.00,...,4.200000e+02,True,False,5,False,False,False,False,False,599.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3790,01t8n000000GwvPAAS,9054,16448,Lovely Professional University,"BBA, LL.B. (Hons.)",Intermediate,Years,5.0,1200000.0,1200000.00,...,1.576800e+08,False,False,1,False,False,False,False,False,562.10
3791,01t8n000000GrsuAAC,6842,15579,Masters Union,Undergraduate Programme,Beginner,Years,6.0,NaN,2925000.00,...,1.892160e+08,False,False,1,False,False,False,False,False,562.09
3792,prfwoo5mcq,27775,25999,IMI Delhi,Post Graduate Diploma in Management (Online),Advanced,Years,24.0,295000.0,295000.00,...,7.568640e+08,False,False,1,False,False,False,False,False,562.08
3793,01t8n000000GrxEAAS,7140,17371,upGrad,MBA Leading Business Transformation,Advanced,Months,585.0,365000.0,1344753.00,...,1.538559e+09,False,False,1,False,False,False,False,False,562.07
3794,01t8n000000GrYbAAK,5575,16657,Edudelphi,Certified Fraud Examiner Course in India,Advanced,nan,NaN,NaN,450.00,...,NaN,False,False,1,False,False,False,False,False,562.06

In [19]:
non_corporate_0_df = non_corporate_0_df.sort_values(
    by=["Duration_in_seconds", "Integration", "inr_amount__c"],
    ascending=[True, False, True]
).reset_index(drop=True)

# Assign sequence rankings based on sorted order
non_corporate_0_df['Rank'] = 550 - (non_corporate_0_df.index * 0.01)
non_corporate_0_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp,Udemy,ABC_coursera,ABC,Rank
0,prha028n6z,10900,17663,Skillfloor,Certified Data Scientist Professional,Beginner,Month,3.0,40000.0,60000.00,...,3.0,True,False,0,True,False,False,False,False,550.00
1,prlag2pjhr,27842,26220,Edureka,Linux Administration Certification Training Co...,Beginner,Week,7.5,23594.0,17995.00,...,7.5,True,False,0,True,False,False,False,False,549.99
2,01t8n000000Gx1RAAS,9428,15717,Unext,Integrated Program In Business Analytics,Advanced,Month,10.0,305836.0,305836.00,...,10.0,True,False,0,True,False,False,False,False,549.98
3,01t8n000000JE72AAG,10013,16508,Skill Smith,Master React Native Program Offline,Advanced,Minutes,3.0,9.0,777.29,...,180.0,True,False,0,True,False,False,False,False,549.97
4,01t8n000000JE6wAAG,10007,15551,Skill Smith,Java Booster Program Offline,Advanced,Minutes,3.0,15.0,118000.00,...,180.0,True,False,0,True,False,False,False,False,549.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1146,01tTZ000000gx2DYAQ,10560,5937,The Design Village Easebuzz,Transportation And Mobility Design,Beginner,Years,4.0,2200000.0,2200000.00,...,126144000.0,False,False,0,True,False,False,False,False,538.54
1147,01tTZ000000gwFWYAY,10541,5922,The Design Village Easebuzz,Product Design,Beginner,Years,4.0,2200000.0,2200000.00,...,126144000.0,False,False,0,True,False,False,False,False,538.53
1148,01tTZ000000gwEvYAI,10504,5894,The Design Village Easebuzz,Interaction & Ux Design,Beginner,Years,4.0,2200000.0,2200000.00,...,126144000.0,False,False,0,True,False,False,False,False,538.52
1149,01t8n000000GrstAAC,6841,16928,Masters Union,UG Programme in Tech and Business Management,Intermediate,Years,4.0,NaN,4368000.00,...,126144000.0,False,False,0,True,False,False,False,False,538.51
1150,01t8n000000GreMAAS,5940,14641,Fireblaze AI School,SQL for Data Science,Advanced,nan,NaN,NaN,2499.00,...,NaN,False,False,0,True,False,False,False,False,538.50

In [20]:
non_corporate_priority_cpp_df= non_corporate_priority_cpp_df.sort_values(
    by=["Duration_in_seconds", "inr_amount__c"],
    ascending=[True,True]
).reset_index(drop=True)

# Assign sequence rankings based on sorted order
non_corporate_priority_cpp_df['Rank'] = 700 - (non_corporate_priority_cpp_df.index * 0.01)
non_corporate_priority_cpp_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp,Udemy,ABC_coursera,ABC,Rank
0,pr140tds7q,21046,18972,Eduonix,Business Analytics for Beginners,Beginner,Minutes,15.00,22488.0,22488.0,...,900.0,True,False,1,False,True,False,False,False,700.00
1,prrv19u96h,21052,18978,Eduonix,Web Accessibility for an Inclusive online pres...,Beginner,Hours,1.00,1500.0,5500.0,...,3600.0,True,False,0,True,True,False,False,False,699.99
2,prwelgdjic,21043,18969,Eduonix,"Start Simple Coding with HTML , CSS and JavaSc...",Beginner,Hours,1.05,10000.0,10000.0,...,3780.0,True,False,2,False,True,False,False,False,699.98
3,pr2aa9dt8x,21053,18979,Eduonix,UIUX with Figma,Beginner,Hours,1.13,1500.0,5599.0,...,4068.0,True,False,0,True,True,False,False,False,699.97
4,pr0or3bd6t,21049,18975,Eduonix,Microsoft Bot Framework v4 - Real Life Example...,Beginner,Minutes,68.00,12500.0,12500.0,...,4080.0,True,False,1,False,True,False,False,False,699.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2049,prwka30dss,32957,32805,Henry Harvin,Advanced Human Resource Management Course (Liv...,Advanced,Years,4.00,349500.0,349500.0,...,126144000.0,False,False,2,False,True,False,False,False,679.51
2050,pr96zqow82,32296,32109,Henry Harvin,Advanced Human Resource Management Course (Ins...,Beginner,Years,4.00,349500.0,349500.0,...,126144000.0,False,False,4,False,True,False,False,False,679.50
2051,prevunsc7b,32809,32627,Henry Harvin,Industry Expert Program in Finance and Account...,Beginner,Years,4.00,498000.0,498000.0,...,126144000.0,False,False,3,False,True,False,False,False,679.49
2052,pr4zjtodwa,33700,33605,Henry Harvin Education,Industry Expert Program in Finance and Account...,Intermediate,Years,4.00,498000.0,498000.0,...,126144000.0,False,False,1,False,True,False,False,False,679.48
2053,prqu6t1ijt,35459,36150,Henry Harvin,Masters (MS) in Digital Marketing,Beginner,Months,288.00,NaN,22500.0,...,757444608.0,False,False,1,False,True,False,False,False,679.47

Ranking ABC

In [21]:
abc_coursera_0_df = abc_coursera_0_df.sort_values(
    by=["Duration_in_seconds", "Integration", "inr_amount__c"],
    ascending=[True, False, True]
).reset_index(drop=True)

# Assign sequence rankings based on sorted order
abc_coursera_0_df['Rank'] = 510 - (abc_coursera_0_df.index * 0.01)
abc_coursera_0_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp,Udemy,ABC_coursera,Rank
0,prai5zubue,14804,14664,Coursera,Static Website Hosting and Cross-Region Replic...,Beginner,Hours,0.1,1.0,0.0,...,NaN,360.0,True,False,0,True,False,False,True,510.00
1,priofhwu49,14375,10553,Coursera,Create a Boggle Word Solver using recursion in...,Intermediate,Hours,0.1,1.0,0.0,...,NaN,360.0,True,False,0,True,False,False,True,509.99
2,prj50a1zil,16862,11768,Coursera,Fast Typer Game using Pygame,Beginner,Hours,0.1,1.0,0.0,...,NaN,360.0,True,False,0,True,False,False,True,509.98
3,prpp90zk8u,18219,14252,Coursera,Recreate the First Ever Easter Egg from Advent...,Beginner,Hours,0.1,1.0,0.0,...,NaN,360.0,True,False,0,True,False,False,True,509.97
4,prrtje596c,15301,14737,Coursera,Style Images with CSS,Intermediate,Hours,0.1,1.0,0.0,...,NaN,360.0,True,False,0,True,False,False,True,509.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1058,prnkxi2dfy,15752,20942,Coursera,Maximizing Marketing Success with Generative A...,Beginner,Hours,NaN,1.0,0.0,...,NaN,NaN,False,False,0,True,False,False,True,499.42
1059,prtq8fe2jo,22555,20634,Coursera,"Concepts, Strategies, and Analytics in Perform...",Beginner,Hours,NaN,1.0,0.0,...,NaN,NaN,False,False,0,True,False,False,True,499.41
1060,prw7ivef80,15593,20515,Coursera,Hotel Digital Marketing and Social Media Strategy,Beginner,Hours,NaN,1.0,0.0,...,NaN,NaN,False,False,0,True,False,False,True,499.40
1061,prwbrwx3rr,22534,20612,Coursera,Google Advanced Data Analytics,Beginner,Hours,NaN,1.0,0.0,...,NaN,NaN,False,False,0,True,False,False,True,499.39
1062,prx3ri6kt5,17517,20952,Coursera,jQuery Tutorial,Beginner,Hours,NaN,1.0,0.0,...,NaN,NaN,False,False,0,True,False,False,True,499.38

In [22]:

abc_coursera_df = abc_coursera_df.sort_values(
    by=["Duration_in_seconds", "Integration", "inr_amount__c"],
    ascending=[True, False, True]
).reset_index(drop=True)

# Assign sequence rankings based on sorted order
abc_coursera_df['Rank'] = 525 - (abc_coursera_df.index * 0.01)
abc_coursera_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp,Udemy,ABC_coursera,Rank
0,pr191gx295,19528,9449,Coursera,Analyze Text Data with Yellowbrick,Intermediate,Hours,0.1,1.0,0.0,...,4887,360.0,True,False,1,False,False,False,True,525.00
1,pr1mfracxt,20031,12536,Coursera,Improving Math Engagement with Prodigy,Beginner,Hours,0.1,1.0,0.0,...,6061,360.0,True,False,1,False,False,False,True,524.99
2,prabvbpkbt,15387,11282,Coursera,Design and Develop an Obstacles Game using Pyg...,Intermediate,Hours,0.1,1.0,0.0,...,5612,360.0,True,False,1,False,False,False,True,524.98
3,prmlysrlzl,19486,13933,Coursera,Predict Gas Guzzlers using a Neural Net Model ...,Intermediate,Hours,0.1,1.0,0.0,...,"4607 , 4905 , 6669",360.0,True,False,3,False,False,False,True,524.97
4,prny34l21j,20046,10012,Coursera,Building Classroom Community Using Flipgrid,Beginner,Hours,0.1,1.0,0.0,...,5002,360.0,True,False,1,False,False,False,True,524.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5439,przhd3q074,22533,20611,Coursera,Learn Mandarin Chinese: Intermediate,Beginner,Hours,NaN,1.0,0.0,...,"6061 , 6213",NaN,False,False,2,False,False,False,True,470.61
5440,przixvhfo5,22618,20702,Coursera,Privacy and Standardisation,Beginner,Hours,NaN,1.0,0.0,...,4934,NaN,False,False,1,False,False,False,True,470.60
5441,przqenabsa,22672,20761,Coursera,Teach English: Intermediate Grammar,Beginner,Hours,NaN,1.0,0.0,...,9606,NaN,False,False,1,False,False,False,True,470.59
5442,przy2ytv16,21460,19450,Coursera,Database Design and Operational Business Intel...,Beginner,Hours,NaN,1.0,0.0,...,4705,NaN,False,False,1,False,False,False,True,470.58
5443,pro59osu24,22748,20841,Coursera,Academic English: Writing,Beginner,Hours,NaN,1.0,0.0,...,6213,NaN,False,False,1,False,False,False,True,470.57

In [23]:
abc_df = abc_df.sort_values(
    by=["Duration_in_seconds", "Integration", "inr_amount__c"],
    ascending=[True, False, True]
).reset_index(drop=True)

# Assign sequence rankings based on sorted order
abc_df['Rank'] = 425 - (abc_df.index * 0.01)
abc_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp,Udemy,ABC_coursera,ABC,Rank
0,pr6ggb6crn,13720,9169,GVC,Sharing Multiple Screens Simultaneously,Beginner,Hours,0.01,1.0,0.0,...,36.0,True,False,1,False,False,False,False,True,425.00
1,prz439vl3r,12700,8151,GVC,Scheduling a Meeting with Outlook,Beginner,Hours,0.01,1.0,0.0,...,36.0,True,False,1,False,False,False,False,True,424.99
2,prwjj6sgg7,13783,19765,GVC,Recognizing and Addressing Micro-behaviors in ...,Beginner,Hours,0.01,1.0,0.0,...,36.0,True,False,1,False,False,False,False,True,424.98
3,pr0ramdk0c,13667,9117,GVC,Closed Captioning,Beginner,Hours,0.02,1.0,0.0,...,72.0,True,False,1,False,False,False,False,True,424.97
4,prnl3tqozi,13112,8562,GVC,Sharing Your Screen,Beginner,Hours,0.02,1.0,0.0,...,72.0,True,False,1,False,False,False,False,True,424.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2493,przpiipjwv,22448,20398,GVC,Outlook on the Web: Using & Managing the Calendar,Beginner,Hours,NaN,1.0,0.0,...,NaN,False,False,1,False,False,False,False,True,400.07
2494,przsnkj6o1,22075,20025,GVC,Configure Windows Defender on a Windows System...,Beginner,Hours,NaN,1.0,0.0,...,NaN,False,False,1,False,False,False,False,True,400.06
2495,przurvq0im,22264,20214,GVC,CompTIA Linux+: SELinux & AppArmor,Intermediate,Hours,NaN,1.0,0.0,...,NaN,False,False,1,False,False,False,False,True,400.05
2496,przvahytsh,22157,20107,GVC,Outlook 2016 (Mac): Sending & Receiving Email,Beginner,Hours,NaN,1.0,0.0,...,NaN,False,False,1,False,False,False,False,True,400.04
2497,przyu0in9m,22779,20873,GVC,Microsoft Azure Services and Lifecycles,Beginner,Hours,NaN,1.0,0.0,...,NaN,False,False,1,False,False,False,False,True,400.03

In [24]:
abc_0_df = abc_0_df.sort_values(
    by=["Duration_in_seconds", "Integration", "inr_amount__c"],
    ascending=[True, False, True]
).reset_index(drop=True)

# Assign sequence rankings based on sorted order
abc_0_df['Rank'] = 350 - (abc_0_df.index * 0.01)
abc_0_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp,Udemy,ABC_coursera,ABC,Rank
0,prkbticw4m,13061,8511,GVC,Is Your Internet FAST Enough?,Beginner,Hours,0.11,1.0,0.0,...,396.0,True,False,0,True,False,False,False,True,350.00
1,prcr33dsjs,13008,8458,GVC,What is Data and Digital Content,Beginner,Hours,0.17,1.0,0.0,...,612.0,True,False,0,True,False,False,False,True,349.99
2,pr8l3huhxx,13084,8534,GVC,Prospecting: Panning for Sales Gold,Beginner,Hours,0.20,1.0,0.0,...,720.0,True,False,0,True,False,False,False,True,349.98
3,prk4u6jgyu,12654,8105,GVC,Introduction to Power Virtual Agents,Beginner,Hours,0.22,1.0,0.0,...,792.0,True,False,0,True,False,False,False,True,349.97
4,pr54fqvljc,12740,8191,GVC,AWS SysOps Associate: AWS Directory Services &...,Intermediate,Hours,0.30,1.0,0.0,...,1080.0,True,False,0,True,False,False,False,True,349.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,prkyuckt6g,22822,20916,GVC,Business intelligence and data warehousing,Beginner,Hours,NaN,1.0,0.0,...,NaN,False,False,0,True,False,False,False,True,349.24
77,prlzsqg3kg,22764,20858,GVC,Python Data Visualization,Beginner,Hours,NaN,1.0,0.0,...,NaN,False,False,0,True,False,False,False,True,349.23
78,proo82aici,22823,20917,GVC,Introduction to MongoDB,Beginner,Hours,NaN,1.0,0.0,...,NaN,False,False,0,True,False,False,False,True,349.22
79,prp279k851,21916,19866,GVC,Collaboration,Beginner,Hours,NaN,1.0,0.0,...,NaN,False,False,0,True,False,False,False,True,349.21
80,prxxilay2h,21520,19565,GVC,Project Scheduling: Estimate Activity Durations,Beginner,Hours,NaN,1.0,0.0,...,NaN,False,False,0,True,False,False,False,True,349.20

Ranking Udemy_courses

In [25]:
udemy_df = udemy_df.sort_values(
    by=["Duration_in_seconds", "Integration", "inr_amount__c"],
    ascending=[True, False, True]
).reset_index(drop=True)

# Assign sequence rankings based on sorted order
udemy_df['Rank'] = 300 - (udemy_df.index * 0.01)
udemy_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp,Udemy,Rank
0,pr0y1ipl5c,31002,29558,Udemy,Project Management Certified Associate: CAPM P...,Intermediate,Hours,0.1,0.0,23850.0,...,37,4590,360.0,True,False,1,False,False,True,300.00
1,pr3362upkq,31204,29760,Udemy,SAFE 6.0 Scrum Master - Certified SAFE 6 Scrum...,Beginner,Hours,0.1,0.0,23850.0,...,263,5724,360.0,True,False,1,False,False,True,299.99
2,prcdxzvedk,31166,29722,Udemy,ISO 22301Business Continuity Management (BCM &...,Beginner,Hours,0.1,0.0,23850.0,...,40,"4586 , 5436",360.0,True,False,2,False,False,True,299.98
3,prgw6evcc9,31137,29693,Udemy,Project Management - Theory of Constraints way...,Beginner,Hours,0.1,0.0,23850.0,...,37,4590,360.0,True,False,1,False,False,True,299.97
4,prhzt6h99t,31340,29896,Udemy,Life Insurance & Annuity Ultimate Buyers Guide,Beginner,Hours,0.1,0.0,23850.0,...,45,4568,360.0,True,False,1,False,False,True,299.96
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5260,5OqCv2Pw,25043,23264,Udemy,Selenium Java : Beginner to Advanced [Live Pro...,Beginner,Minutes,11327.0,23850.0,23850.0,...,103,"6817 , 6849",679620.0,False,False,2,False,False,True,247.40
5261,3TgEl5Xn,27077,25300,Udemy,"SAP ABAP, OOPS, CROSSAPP, WEBDYNPRO, WORKFLOW,...",Beginner,Minutes,11547.0,23850.0,23850.0,...,316,6938,692820.0,False,False,1,False,False,True,247.39
5262,prbgu9bqhd,33590,33488,Udemy,KPI and metrics for Management Consultants & M...,Advanced,Hours,334.0,22842.0,23850.0,...,63,5506,1202400.0,False,False,1,False,False,True,247.38
5263,prpnv1ebe6,33589,33487,Udemy,Critical Thinker Academy: Learn to Think Like ...,Intermediate,Hours,1173.0,22842.0,23850.0,...,314,"5025 , 7005 , 7006 , 7007 , 7008 , 7009 , 7010...",4222800.0,False,False,10,False,False,True,247.37
5264,prz666dzq4,29616,28785,Udemy,ISC2 Certified in Cybersecurity (CC) Full Prac...,Beginner,Minutes,NaN,23850.0,23850.0,...,130,6063,NaN,False,False,1,False,False,True,247.36

In [26]:
udemy_0_df = udemy_0_df.sort_values(
    by=["Duration_in_seconds", "Integration", "inr_amount__c"],
    ascending=[True, False, True]
).reset_index(drop=True)

# Assign sequence rankings based on sorted order
udemy_0_df['Rank'] = 200 - (udemy_0_df.index * 0.01)
udemy_0_df

,product_sfid,product_id,mpid,course_provider_platform_name__c,product_name,course_level,duration_medium__c,course_duration__c,price__c,loan_amount__c,...,skill_id,concepts,Duration_in_seconds,Is_within_a_week,Integration,concept_count,no_concept,priority_cpp,Udemy,Rank
0,prckjmlvhq,29660,28123,Udemy,Managing a Global Team with Confidence,Beginner,Minutes,35.0,23850.0,23850.0,...,255,NaN,2100.0,True,False,0,True,False,True,200.00
1,prtvhr73po,28604,27070,Udemy,Visionary Servant Leadership,Beginner,Minutes,84.0,23850.0,23850.0,...,255,NaN,5040.0,True,False,0,True,False,True,199.99
2,prgxo3e70m,29720,28183,Udemy,Leadership Skills: Learn Vigilant Leadership &...,Beginner,Minutes,89.0,23850.0,23850.0,...,255,NaN,5340.0,True,False,0,True,False,True,199.98
3,prbg329x5m,28263,26729,Udemy,"Leadership: How to Influence, Inspire and Impa...",Beginner,Minutes,91.0,23850.0,23850.0,...,255,NaN,5460.0,True,False,0,True,False,True,199.97
4,preelbycur,29646,28109,Udemy,Leadership - Rise of a Leader (Lead people wit...,Beginner,Minutes,91.0,23850.0,23850.0,...,255,NaN,5460.0,True,False,0,True,False,True,199.96
5,prllet9osu,30939,29495,Udemy,Manage Change Through Collaboration and Team Work,Beginner,Minutes,102.0,0.0,23850.0,...,262,NaN,6120.0,True,False,0,True,False,True,199.95
6,prr7lx775u,29532,27995,Udemy,Leading & Managing People [Effectively],Beginner,Minutes,119.0,23850.0,23850.0,...,255,NaN,7140.0,True,False,0,True,False,True,199.94
7,pr4rce05qb,30210,28673,Udemy,"Ethical AI Decision Making, Insights for Leade...",Beginner,Minutes,126.0,23850.0,23850.0,...,261,NaN,7560.0,True,False,0,True,False,True,199.93
8,prrn4jj0va,28014,26480,Udemy,"Management - Leadership, Negotiating, Assertiv...",Beginner,Minutes,128.0,23850.0,23850.0,...,255,NaN,7680.0,True,False,0,True,False,True,199.92
9,prxn9li6ss,31017,29573,Udemy,Collaboration with Emotional Intelligence,Intermediate,Minutes,184.0,0.0,23850.0,...,262,NaN,11040.0,True,False,0,True,False,True,199.91
10,8ObDt0Ty,23451,21672,Udemy,Master SWOT Analysis and Business Strategy f...,Beginner,Minutes,185.0,23850.0,23850.0,...,49,NaN,11100.0,True,False,0,True,False,True,199.90
11,prz8qyxwm0,28009,26475,Udemy,"How to Lead with Ease & Be a Successful CEO, L...",Beginner,Minutes,186.0,23850.0,23850.0,...,255,NaN,11160.0,True,False,0,True,False,True,199.89
12,pr48w18bp0,28040,26506,Udemy,Leadership: Practical Leadership Skills,Beginner,Minutes,200.0,23850.0,23850.0,...,255,NaN,12000.0,True,False,0,True,False,True,199.88
13,prgh28omad,30150,28613,Udemy,Web Performance In Practice: Master Core Web V...,Beginner,Minutes,204.0,23850.0,23850.0,...,106,NaN,12240.0,True,False,0,True,False,True,199.87
14,7BpKm9Gj,23448,21669,Udemy,"Master PMP Cost Management: Plan, Budget, Esti...",Beginner,Minutes,224.0,23850.0,23850.0,...,49,NaN,13440.0,True,False,0,True,False,True,199.86
15,prz4qvhvi9,30188,28651,Udemy,Professional Diploma in Advertising and Public...,Beginner,Minutes,251.0,23850.0,23850.0,...,262,NaN,15060.0,True,False,0,True,False,True,199.85
16,prtq3w17ir,29930,28393,Udemy,Product Owner II for Agile Intermediate: Certi...,Beginner,Minutes,379.0,23850.0,23850.0,...,36,NaN,22740.0,True,False,0,True,False,True,199.84
17,5TgAx9Cg,22983,21204,Udemy,Certified Key Performance Indicators Professio...,Beginner,Minutes,448.0,23850.0,23850.0,...,49,NaN,26880.0,True,False,0,True,False,True,199.83
18,2FeBo7Oj,25745,23967,Udemy,AWS Technical Essentials - Hands-On Training ...,Beginner,Minutes,866.0,23850.0,23850.0,...,44,NaN,51960.0,True,False,0,True,False,True,199.82
19,pr72kec05o,27984,26450,Udemy,Lean Six Sigma Green Belt Online Course (2023),Beginner,Minutes,967.0,23850.0,23850.0,...,39,NaN,58020.0,True,False,0,True,False,True,199.81
20,5YrGr8Hy,22895,21116,Udemy,Automated Cryptocurrency Portfolio Investing w...,Beginner,Minutes,1931.0,23850.0,23850.0,...,49,NaN,115860.0,True,False,0,True,False,True,199.80
21,1FkNf0Wo,22871,21092,Udemy,ACCA MA (F2) A Complete Course on Management A...,Beginner,Minutes,2014.0,23850.0,23850.0,...,261,NaN,120840.0,True,False,0,True,False,True,199.79
22,prv7lg5yyb,29127,27590,Udemy,Leadership & Management Skills: 2-in-1 Masterc...,Beginner,Minutes,2655.0,23850.0,23850.0,...,255,NaN,159300.0,True,False,0,True,False,True,199.78

Concanating all the dataframe

In [ ]:
pieces = {"x1":non_corporate_priority_cpp_df,"x2": non_corporate_df,"x3":non_corporate_0_df, "y":abc_coursera_df,"y1":abc_coursera_0_df,"y2": abc_df,"y3": abc_0_df, "z": udemy_df,"z1": udemy_0_df}
result = pd.concat(pieces)
result.to_excel("C:\\Users\\taslim.siddiqui\\Downloads\\Recorating_25-07-2025.xlsx")
print(result)

      product_sfid  product_id   mpid course_provider_platform_name__c  \
x1 0    pr140tds7q       21046  18972                          Eduonix
   1    prrv19u96h       21052  18978                          Eduonix
   2    prwelgdjic       21043  18969                          Eduonix
   3    pr2aa9dt8x       21053  18979                          Eduonix
   4    pr0or3bd6t       21049  18975                          Eduonix
...            ...         ...    ...                              ...
z1 18     2FeBo7Oj       25745  23967                            Udemy
   19   pr72kec05o       27984  26450                            Udemy
   20     5YrGr8Hy       22895  21116                            Udemy
   21     1FkNf0Wo       22871  21092                            Udemy
   22   prv7lg5yyb       29127  27590                            Udemy

                                            product_name course_level  \
x1 0                    Business Analytics for Beginners     Beginner
   1   Web Accessibility for an Inclusive online pres...     Beginner
   2   Start Simple Coding with HTML , CSS and JavaSc...     Beginner
   3                                     UIUX with Figma     Beginner
   4   Microsoft Bot Framework v4 - Real Life Example...     Beginner
...                                                  ...          ...
z1 18  AWS Technical Essentials  - Hands-On Training ...     Beginner
   19     Lean Six Sigma Green Belt Online Course (2023)     Beginner
   20  Automated Cryptocurrency Portfolio Investing w...     Beginner
   21  ACCA MA (F2) A Complete Course on Management A...     Beginner
   22  Leadership & Management Skills: 2-in-1 Masterc...     Beginner

      duration_medium__c  course_duration__c  price__c  loan_amount__c  ...  \
x1 0             Minutes               15.00   22488.0         22488.0  ...
   1               Hours                1.00    1500.0          5500.0  ...
   2               Hours                1.05   10000.0         10000.0  ...
   3               Hours                1.13    1500.0          5599.0  ...
   4             Minutes               68.00   12500.0         12500.0  ...
...                  ...                 ...       ...             ...  ...
z1 18            Minutes              866.00   23850.0         23850.0  ...
   19            Minutes              967.00   23850.0         23850.0  ...
   20            Minutes             1931.00   23850.0         23850.0  ...
   21            Minutes             2014.00   23850.0         23850.0  ...
   22            Minutes             2655.00   23850.0         23850.0  ...

       Duration_in_seconds  Is_within_a_week Integration  concept_count  \
x1 0                 900.0              True       False              1
   1                3600.0              True       False              0
   2                3780.0              True       False              2
   3                4068.0              True       False              0
   4                4080.0              True       False              1
...                    ...               ...         ...            ...
z1 18              51960.0              True       False              0
   19              58020.0              True       False              0
   20             115860.0              True       False              0
   21             120840.0              True       False              0
   22             159300.0              True       False              0

       no_concept  priority_cpp  Udemy  ABC_coursera    ABC    Rank
x1 0        False          True  False         False  False  700.00
   1         True          True  False         False  False  699.99
   2        False          True  False         False  False  699.98
   3         True          True  False         False  False  699.97
   4        False          True  False         False  False  699.96
...           ...           ...    ...           ...    ...     ...
z1 18        True         False   True           NaN    NaN  199.82
   19        True         False   True           NaN    NaN  199.81
   20        True         False   True           NaN    NaN  199.80
   21        True         False   True           NaN    NaN  199.79
   22        True         False   True           NaN    NaN  199.78

[21374 rows x 23 columns]

testing

In [28]:
result_reset = result.reset_index()
result_reset['final_rank'] = 600 - (result_reset.index * 0.01)
#result_reset.to_excel("/Users/romitbenkar/Downloads/Recorating_21-03-2025.xlsx")

In [29]:
import pandas as pd

# Define the dataset
data = {
    "duration_seconds": [2000, 5890, 5739, 6746, 2000, 2000, 5890, 2000, 67383, 784892, 6474, 5890],
    "Integration": [True, True, False, True, True, True, True, True, False, True, False, False],
    "Price": [5943843, 7744, 4744, 84433, 74484, 4438, 46746, 73782, 74383, 74873, 764673, 64473]
}

# Create a DataFrame
df = pd.DataFrame(data)

# Sort by the three columns in the desired order: duration_seconds, Integration (descending), Price
df = df.sort_values(
    by=["duration_seconds", "Integration", "Price"],
    ascending=[True, False, True]
).reset_index(drop=True)

# Assign sequence rankings based on sorted order
df['Rank'] = 600 - (df.index * 0.01)

# Display the resulting DataFrame
print(df)

    duration_seconds  Integration    Price    Rank
0               2000         True     4438  600.00
1               2000         True    73782  599.99
2               2000         True    74484  599.98
3               2000         True  5943843  599.97
4               5739        False     4744  599.96
5               5890         True     7744  599.95
6               5890         True    46746  599.94
7               5890        False    64473  599.93
8               6474        False   764673  599.92
9               6746         True    84433  599.91
10             67383        False    74383  599.90
11            784892         True    74873  599.89